"""
Context Continuity & Task Memory Test Suite.
Validates that agents pick up on previous tasks, including:
1. Dev Agent receives and implements specifications defined by PM Agent.
2. Security, QA, and Senior Reviewer Agents ingest prior review/audit history.
3. Security & QA finding handoffs properly trigger Dev remediation with prior error context.
4. Incremental human follow-up comments on an existing PR build on previous commits/branch state.
"""

from __future__ import annotations

import pytest
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

from src.event_router import EventRouter, AgentContextBuilder
from src.llm_runner import LLMRunner
from src.test_harness import TestHarness, TestResult


@pytest.mark.asyncio
async def test_dev_agent_picks_up_pm_specification():
    """
    Ensures Dev Agent context prompt contains the exact user stories, acceptance criteria,
    and requirements generated by previous PM tasks.
    """
    workspace_info = {"has_backend": True, "detected_dirs": ["`backend/`"], "key_configs": ["pytest.ini"]}
    issue_info = {
        "number": 15,
        "title": "Add Excel Parser for Big Spreadsheets",
        "body": "## 🎯 User Story\nAs a Sales Analyst, I want to parse .xlsx files up to 50MB.\n\n### Acceptance Criteria\n- Given a 50MB xlsx file, When uploaded, Then extract chunks in under 3 seconds.",
    }

    context_markdown = AgentContextBuilder.format_context_block(
        workspace_info=workspace_info,
        issue_info=issue_info,
    )

    # Verify context block contains the PM specification elements
    assert "Add Excel Parser for Big Spreadsheets" in context_markdown
    assert "As a Sales Analyst" in context_markdown
    assert "extract chunks in under 3 seconds" in context_markdown
    assert "backend/app/" in context_markdown


@pytest.mark.asyncio
async def test_reviewer_agents_pick_up_prior_review_history():
    """
    Ensures that when a PR has multiple rounds of reviews/comments, subsequent agents
    (Security, QA, Senior Reviewer) pick up and incorporate the prior audit history.
    """
    workspace_info = {"has_backend": True, "detected_dirs": ["`backend/`"], "key_configs": []}
    issue_info = {"number": 20, "title": "Implement Webhook Verification"}
    pr_info = {"number": 22, "branch": "feat/20-webhook-verification", "diff": "+ def verify_signature(): ..."}
    
    prior_reviews = (
        "### 📋 Prior Review & Audit History on this PR:\n"
        "#### 💬 Review by @security-agent (COMMENT):\n"
        "STATUS: PASSED 🛡️ Tenant isolation validated. Constant-time HMAC comparison recommended.\n\n"
        "#### 💬 Review by @qa-agent (COMMENT):\n"
        "STATUS: PASSED 🧪 12/12 unit tests passing.\n"
    )

    context_markdown = AgentContextBuilder.format_context_block(
        workspace_info=workspace_info,
        issue_info=issue_info,
        pr_info=pr_info,
        review_history=prior_reviews,
    )

    # Verify Reviewer Agent receives both the diff AND all previous agent verdicts
    assert "Prior Review & Audit History on this PR" in context_markdown
    assert "@security-agent" in context_markdown
    assert "Constant-time HMAC comparison" in context_markdown
    assert "@qa-agent" in context_markdown
    assert "12/12 unit tests passing" in context_markdown
    assert "verify_signature" in context_markdown


@pytest.mark.asyncio
async def test_security_defects_handed_off_to_dev_for_remediation(tmp_path: Path):
    """
    Simulates Security Agent flagging multi-tenant defects and verifies that Dev Agent
    is invoked with the security findings to produce remediation code.
    """
    harness = MagicMock(spec=TestHarness)
    harness.cwd = str(tmp_path)
    harness.run_command = AsyncMock(return_value=TestResult(command="", exit_code=0, duration_seconds=0.1, stdout="passed", stderr=""))

    router = EventRouter(dry_run=False, test_harness=harness)
    router.github_client = MagicMock()
    router.github_client.token = "test-token"
    router.github_client.get_pr_diff = AsyncMock(return_value="+ def query_all(): return db.query(TenantData).all()")
    router.github_client.get_pr_reviews = AsyncMock(return_value=[])
    router.github_client.get_issue_comments = AsyncMock(return_value=[])
    router.github_client.create_issue_comment = AsyncMock(return_value={"id": 201})
    router.github_client.create_pr_review = AsyncMock(return_value={"id": 301})

    # Track prompts received by LLM Runner
    received_prompts = []

    async def mock_generate_response(system_inst, user_prompt, dry_run=False, tier="fast"):
        received_prompts.append(user_prompt)
        return (
            "### Remediation Update\n"
            "```python:backend/app/query.py\ndef query_by_tenant(tenant_id: str):\n    return db.query(TenantData).filter_by(tenant_id=tenant_id).all()\n```"
        )

    router.llm_runner.generate_response = AsyncMock(side_effect=mock_generate_response)

    (tmp_path / "backend").mkdir(parents=True)

    # Simulate security findings comment payload
    payload = {
        "action": "created",
        "repository": {"full_name": "dipeshsingh2012/rfpengine"},
        "pull_request": {"number": 8, "head": {"ref": "feat/8-multi-tenant-data"}},
        "comment": {
            "body": "STATUS: BLOCKED 🛑 Critical Finding: Missing `tenant_id` filter on queries in `query.py`.",
            "user": {"login": "security-agent"},
        },
    }

    result = await router.route_event("pull_request_review_comment", payload)

    # Verify dev agent was invoked with the exact security defect context
    assert result["agent"] == "dev-agent"
    assert result["action"] == "remediated_pr"
    assert any("Missing `tenant_id` filter" in p for p in received_prompts)


@pytest.mark.asyncio
async def test_incremental_human_comment_preserves_existing_pr_state(tmp_path: Path):
    """
    Ensures that when a human comments on an existing PR, the fleet router picks up
    the existing PR number and branch instead of generating a new duplicate PR.
    """
    harness = MagicMock(spec=TestHarness)
    harness.cwd = str(tmp_path)
    harness.run_command = AsyncMock(return_value=TestResult(command="", exit_code=0, duration_seconds=0.1, stdout="15 passed", stderr=""))

    router = EventRouter(dry_run=True, test_harness=harness)
    (tmp_path / "backend").mkdir(parents=True)

    # Comment on existing PR #14
    payload = {
        "action": "created",
        "repository": {"full_name": "dipeshsingh2012/rfpengine"},
        "pull_request": {
            "number": 14,
            "title": "feat: add vector embeddings",
            "head": {"ref": "feat/14-vector-embeddings"},
            "labels": [{"name": "ready-for-review"}],
        },
        "comment": {
            "body": "Please also add dimension validation check for 768 vs 1536.",
            "user": {"login": "lead-architect"},
        },
    }

    result = await router.route_event("pull_request_review_comment", payload)

    assert result["pipeline"] == "autonomous-5-agent-sdlc"
    # Verify PM and Dev step detection recognized the existing PR
    assert result["stages"]["pm_agent"]["status"] == "skipped"
    assert result["stages"]["dev_agent"]["status"] == "skipped"
    assert result["stages"]["dev_agent"]["pr_number"] == 14
    assert result["stages"]["dev_agent"]["branch_name"] == "feat/14-vector-embeddings"
    assert result["status"] == "completed_awaiting_human_merge"
